[package]
name = "v-clickhouse-rs"
version = "0.2.0-alpha.7"
authors = ["Mikhail Sukharev <suharev7@gmail.com>"]
license = "MIT"
homepage = "https://github.com/suharev7/clickhouse-rs"
repository = "https://github.com/suharev7/clickhouse-rs"
description = "Asynchronous Yandex ClickHouse client library."
documentation = "https://docs.rs/clickhouse-rs/"
readme = "README.md"
keywords = ["tokio", "database", "clickhouse"]
categories = ["database"]
edition = "2018"
exclude = ["tests/*", "examples/*"]

[features]
default = ["tokio_io"]
tls = ["tokio-tls", "native-tls"]
async_std = ["async-std"]
tokio_io = ["tokio"]

[dependencies]
byteorder = "^1.3"
chrono = "0.4"
chrono-tz = "=0.5.2"
crossbeam = "0.7.3"
thiserror = "1.0.20"
futures-core = "0.3.5"
futures-sink = "0.3.5"
hostname = "^0.3"
lazy_static = "1.4.0"
lz4 = "1.23.2"
pin-project = "0.4.23"
url="^2"
uuid = "0.8.1"
combine = "4.2.3"

[dependencies.futures-util]
version = "0.3.5"
features = ["sink"]

[dependencies.tokio]
version = "0.2.22"
default-features = false
features = ["io-util", "time", "net", "sync", "rt-threaded"]
optional = true

[dependencies.async-std]
version = "1.6"
optional = true

[dependencies.clickhouse-rs-cityhash-sys]
path = "clickhouse-rs-cityhash-sys"
version = "0.1.2"

[dependencies.log]
version = "0.4.8"
features = ["std", "serde"]

[dependencies.native-tls]
version = "0.2"
optional = true

[dependencies.tokio-tls]
version = "0.3.1"
optional = true

[dev-dependencies]
env_logger = "^0.7"
rand = "^0.7"

[dev-dependencies.tokio]
version = "0.2.0"
default-features = false
features = ["macros"]
